version: '3.8'

services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_DB: smart_budget
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
      image: prom/prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
        - ./prometheus:/prometheus
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        monitoring:
          aliases:
            - prometheus
networks:
  monitoring: